title: Humas
description: Data and Society.
author: Haomin Lin
avatar: /logo.png
email: humaslin97@gatech.edu

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Robauther_Lin
  card: summary
logo: logo.png
social:
  name: Haomin Lin
  links:
    - https://twitter.com/Robauther_Lin
    - https://www.facebook.com/haomin.lin.927/
    - https://www.linkedin.com/in/humaslin/
    - https://github.com/HumasLin
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
